language: node_js

node_js:
  - "node"

env:
  - NODE_ENV=test

services:
  - postgresql

before_script:
  - psql -c 'create database mydiary;' -U postgres

cache:
  directories:
    - "node_modules"

after_success: 
  - nyc npm test && nyc report --reporter=text-lcov | coveralls